#!/usr/bin/env python

import sys,os.path
from Python.ert_core  import ert_core
from Python.ert_utils import *

exe_path = os.path.dirname(sys.argv[0])
if exe_path == "":
  exe_path = "."

ert = ert_core()

ert.exe_path = exe_path

if ert.flags() != 0:
  sys.stderr.write("\n--- Parsing command line arguments failed --- \n\n")
  sys.exit(1)
sys.stdout.flush()

if ert.configure() != 0:
  sys.stderr.write("\n--- Configuring ERT failed ---\n\n")
  sys.exit(1)
sys.stdout.flush()

flops_list = parse_int_list(ert.dict["ERT_FLOPS"][0])

for flop in flops_list:
  print
  print "FLOP count %d..." % flop
  sys.stdout.flush()

  ert.flop = flop

  ert.flop_dir = "%s/FLOPS.%03d" % (ert.results_dir,flop)
  make_dir_if_needed(ert.flop_dir,"run")

  if ert.build() != 0:
    sys.stderr.write("\n--- Building ERT failed ---\n\n")
    sys.exit(1)
  sys.stdout.flush()

  if ert.run() != 0:
    sys.stderr.write("\n--- Running ERT failed ---\n\n")
    sys.exit(1)
  sys.stdout.flush()

  if ert.process() != 0:
    sys.stderr.write("\n--- Processing ERT results failed ---\n\n")
    sys.exit(1)
  sys.stdout.flush()

  if ert.graphs() != 0:
    sys.stderr.write("\n--- Making ERT individual graphs failed ---\n\n")
    sys.exit(1)
  sys.stdout.flush()

  if ert.database() != 0:
    sys.stderr.write("\n--- Making ERT individual databases failed ---\n\n")
    sys.exit(1)
  sys.stdout.flush()

  print

if ert.roofline() != 0:
  sys.stderr.write("\n--- Making ERT roofline failed ---\n\n")
  sys.exit(1)
sys.stdout.flush()

print
print "+-------------------------------------------------"
print "| Empirical roofline graph:    '%s/roofline.ps'"   % ert.results_dir
print "| Empirical roofline database: '%s/roofline.json'" % ert.results_dir
print "+-------------------------------------------------"
print

sys.exit(0)
